[package]
name = "vdf"
version = "0.1.0"
authors = ["william <williamborgeaud@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ramp = "0.5.3"
sha3 = "0.8.2"
rand = "0.7.2"
rand_core = "0.5.1"